return {
  settings = {
    python = {
      analysis = {
        autoSearchPaths = true,
        useLibraryCodeForTypes = true,
        diagnosticMode = "openFilesOnly",
        typeCheckingMode = "standard",
        autoImportCompletions = true,
        stubPath = "",
        extraPaths = {},
        include = {},
        exclude = {},
        ignore = {},
        diagnosticSeverityOverrides = {
          reportGeneralTypeIssues = "error",
          reportMissingImports = "error",
          reportMissingTypeStubs = "none",
          reportUnusedImport = "warning",
          reportUnusedClass = "warning",
          reportUnusedFunction = "warning",
          reportUnusedVariable = "warning",
          reportDuplicateImport = "warning",
          reportDeprecated = "warning",
          reportUntypedFunctionDecorator = "none",
          reportUntypedClassDecorator = "none",
          reportUntypedBaseClass = "none",
          reportPrivateUsage = "none",
          reportMissingSuperCall = "none",
          reportImplicitStringConcatenation = "none",
          reportOptionalSubscript = "error",
          reportOptionalMemberAccess = "error",
          reportOptionalCall = "error",
          reportOptionalIterable = "error",
          reportOptionalContextManager = "error",
          reportOptionalOperand = "error",
          reportRedeclaration = "error",
          reportReturnType = "error",
          reportArgumentType = "error",
          reportAssignmentType = "error",
          reportCallIssue = "error",
          reportIndexIssue = "error",
          reportOperatorIssue = "error",
          reportUnnecessaryIsInstance = "none",
          reportUnnecessaryCast = "none",
          reportUnnecessaryComparison = "none",
          reportAssertAlwaysTrue = "warning",
          reportSelfClsParameterName = "warning",
          reportUndefinedVariable = "error",
          reportUnboundVariable = "error",
          reportUnhashable = "error",
          reportUnusedCoroutine = "error",
          reportUnusedExcept = "error",
          reportUnreachable = "warning",
          reportMatchNotExhaustive = "warning",
          reportImplicitOverride = "none",
          reportConstantRedefinition = "warning",
          reportIncompatibleMethodOverride = "error",
          reportIncompatibleVariableOverride = "error",
          reportPossiblyUnboundVariable = "error",
        },
      },
    },
  },
}
