return {
  init_options = {
    hostInfo = "neovim",
    maxTsServerMemory = 4096,
    disableAutomaticTypingAcquisition = false,
    locale = "en",
    preferences = {
      autoImportFileExcludePatterns = {},
      autoImportSpecifierExcludeRegexes = {},
      disableSuggestions = false,
      includeInlayParameterNameHints = "literals",
      includeInlayParameterNameHintsWhenArgumentMatchesName = true,
      includeInlayFunctionParameterTypeHints = true,
      includeInlayVariableTypeHints = true,
      includeInlayPropertyDeclarationTypeHints = true,
      includeInlayFunctionLikeReturnTypeHints = true,
      includeInlayEnumMemberValueHints = true,
      importModuleSpecifierPreference = "project-relative",
      importModuleSpecifierEnding = "auto",
      quotePreference = "auto",
      includeCompletionsWithInsertText = true,
      allowTextChangesInNewFiles = true,
      providePrefixAndSuffixTextForRename = true,
      includeAutomaticOptionalChainCompletions = true,
      includeCompletionsWithClassMemberSnippets = true,
      includePackageJsonAutoImports = "auto",
    },
  },
}
