theme = "catppuccin-mocha"

[keybinds]
next = ["Down", "ctrl j"]
previous = ["Up", "ctrl k"]

[providers.actions]
fallback = [
  { action = "menus:open", label = "open", after = "Nothing" },
  { action = "menus:default", label = "run", after = "Close" },
  { action = "menus:parent", label = "back", bind = "Escape", after = "Nothing" },

  { action = "decrease", label = "-5%", bind = "ctrl j", after = "AsyncClearReload" },
  { action = "increase", label = "+5%", bind = "ctrl k", after = "AsyncClearReload" },
]
