layerrule = blur on

layerrule {
  name = no-screen-share-rofi
  no_screen_share = on
  match:namespace = match:namespace ^(rofi)$
}

layerrule = no_screen_share on, match:namespace ^(notifications)$
