$mainMod = SUPER

$browser = zen-beta
$fileManager = dolphin
$menu = rofi -show run
$terminal = kitty

$scripts = ~/.config/hypr/hyprland/scripts
$scriptBlackout = $scripts/blackout.sh
$scriptClipboard = $scripts/clipboard.sh
$scriptGame = $scripts/energy-saver.sh
$scriptScreenshot = $scripts/screenshot.sh
$scriptToggle = $scripts/toggle.sh

$killAllCommand = pkill
# $killAllCommand = ps aux | grep "pattern_to_match" | grep -v grep | awk '{print $2}' | xargs kill
# $killAllCommand = killall

