windowrule {
  name = picture-in-picture-zen
  float = on
  size = 384 216
  pin = on
  move = ((monitor_w*1)-404) (45)
  match:initial_class = ^(zen-beta)$
  match:initial_title = ^(Picture-in-Picture)$
}


windowrule = no_screen_share on, match:initial_class ^(code)$
windowrule = no_screen_share on, match:initial_class ^(zen-beta)$, match:title (.*)(- Google Gemini — Zen Browser)$
windowrule = no_screen_share on, match:initial_class ^(zen-beta)$, match:title ^(Z.ai - Free AI Chatbot & Agent powered by GLM-5.1 & GLM-5 — Zen Browser)$
windowrule = no_screen_share on, match:initial_class ^(zen-beta)$, match:title (Zen Browser Private Browsing)$
windowrule = no_screen_share on, match:initial_class ^(zen-beta)$, match:title ^(\(\d+\) )?WhatsApp — Zen Browser$

windowrule = float on, size 952 522, center on, stay_focused on, match:class (btop)
windowrule = float on, size 952 522, center on, stay_focused on, match:class (yazi)


# Ignore maximize requests from apps
windowrule {
  name = ignore-maximize
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-dragging
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# # Ignore maximize requests from apps
# windowrule = suppress_event maximize, match:class .*
#
# # Fix some dragging issues with XWayland
# windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
