require("hyprland.keybinds.apps")
require("hyprland.keybinds.multimedia")
require("hyprland.keybinds.utilities")
require("hyprland.keybinds.walker")
require("hyprland.keybinds.windows")
require("hyprland.keybinds.workspaces")
